# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 15:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import producers.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('business_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(max_length=8, validators=[producers.validators.validate_uk_postcode])),
                ('phone', models.CharField(max_length=15, validators=[producers.validators.validate_uk_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='producer',
            name='products',
            field=models.ManyToManyField(to='producers.Product'),
        ),
    ]
