# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='temp', help_text='Used in URLs referring to this product.', max_length=30),
            preserve_default=False,
        ),
    ]
