# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Used in URLs referring to this product.', max_length=30, unique=True),
        ),
    ]
