# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0004_product_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['business_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='producer',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Check this to make this Producer visible on the site.'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
