# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0006_auto_20160705_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Check box to make this Producer visible on the site.'),
        ),
    ]
