# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producers', '0007_auto_20160705_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time this item was created in the database.')),
                ('time_modified', models.DateTimeField(auto_now=True, help_text='The time this item was last saved to the database.')),
                ('image', models.ImageField(upload_to='producers')),
                ('is_visible', models.BooleanField(default=True, help_text='Check box to make this Image visible on the site.')),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['-time_created']},
        ),
        migrations.AddField(
            model_name='producerimage',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='producers.Producer'),
        ),
    ]
