django:
  settings_module: madenearyou.settings.vagrant
virtualenv:
  envname: made-near-you
foreman:
  procfile: Procfile_vagrant
db:
  name: madenearyou
  user: madenearyou
  password: madenearyou
use_geodjango: 'true'

